[32m2024-02-05 09:13:19 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 35e34f27-9096-459f-ad5d-9ccb24d4b6c8 - 31711 - LOGS_CAPTURED - Started capturing logs in process (pid: 31711).
[32m2024-02-05 09:13:19 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 35e34f27-9096-459f-ad5d-9ccb24d4b6c8 - 31711 - docs_for_embeddings - STEP_START - Started execution of step "docs_for_embeddings".
[32m2024-02-05 09:13:20 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 35e34f27-9096-459f-ad5d-9ccb24d4b6c8 - docs_for_embeddings - Loading file from: ../chunked_data/combined_and_cleaned_docs using PickledObjectFilesystemIOManager...
[32m2024-02-05 09:13:20 +0100[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 35e34f27-9096-459f-ad5d-9ccb24d4b6c8 - 31711 - docs_for_embeddings - STEP_FAILURE - Execution of step "docs_for_embeddings" failed.

dagster._core.errors.DagsterExecutionLoadInputError: Error occurred while loading input "combined_and_cleaned_docs" of step "docs_for_embeddings"::

FileNotFoundError: [Errno 2] No such file or directory: '../chunked_data/combined_and_cleaned_docs'

Stack Trace:
  File "/Users/szymonzmyslony/Library/Caches/pypoetry/virtualenvs/pipeline-RtkjAAJa-py3.11/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/szymonzmyslony/Library/Caches/pypoetry/virtualenvs/pipeline-RtkjAAJa-py3.11/lib/python3.11/site-packages/dagster/_core/execution/plan/inputs.py", line 831, in _load_input_with_input_manager
    value = input_manager.load_input(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/szymonzmyslony/Library/Caches/pypoetry/virtualenvs/pipeline-RtkjAAJa-py3.11/lib/python3.11/site-packages/dagster/_core/storage/upath_io_manager.py", line 402, in load_input
    return self._load_single_input(path, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/szymonzmyslony/Library/Caches/pypoetry/virtualenvs/pipeline-RtkjAAJa-py3.11/lib/python3.11/site-packages/dagster/_core/storage/upath_io_manager.py", line 256, in _load_single_input
    raise e
  File "/Users/szymonzmyslony/Library/Caches/pypoetry/virtualenvs/pipeline-RtkjAAJa-py3.11/lib/python3.11/site-packages/dagster/_core/storage/upath_io_manager.py", line 239, in _load_single_input
    obj = self.load_from_path(context=context, path=path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/szymonzmyslony/Library/Caches/pypoetry/virtualenvs/pipeline-RtkjAAJa-py3.11/lib/python3.11/site-packages/dagster/_core/storage/fs_io_manager.py", line 283, in load_from_path
    with path.open("rb") as file:
         ^^^^^^^^^^^^^^^
  File "/nix/store/03q8gn91mj95y5bqbcl90hyvmpqpz738-python3-3.11.7/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0m
